version: "3.9"
services:
    app:
        image: golang:1.16.5-alpine
        ports:
            - 8080:8081
        volumes: 
            - .:/go/rest-api
        working_dir: /go/rest-api
        command: go run main.go
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        container_name: goDockerDB
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'gomysql:/var/lib/mysql'
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
volumes:
    gomysql:
        driver: local